# Generated by Django 5.1 on 2024-08-24 23:35

import game_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=game_app.models.game_upload_path),
        ),
    ]
