# Generated by Django 5.1 on 2024-08-25 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0004_developer_publisher_game_developer_game_publisher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Developer',
            new_name='DeveloperTeam',
        ),
    ]
