# Generated by Django 5.1 on 2024-08-24 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='genre',
            new_name='genres',
        ),
    ]
