# Generated by Django 5.1 on 2024-09-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_usergamestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
